### ISSUE TITLE
"Streaming Mode Configuration" in the user guide

### ISSUE THREAD

**Issue by sonebu** [MaximIntegratedAI/MaximAI_Documentation#34]
On the [user guide](https://github.com/MaximIntegratedAI/MaximAI_Documentation/blob/master/MAX78000/MAX78000%20User%20Guide.pdf)
page 388
Table 26-20: CNNx16_n Control Register
bit 14 "Streaming Mode Enable"

There is the following statement: "Refer to Streaming Mode Configuration for additional information."

However, as far as I can tell, there is no section named Streaming Mode Configuration in the user guide. Is this statement referring to an external document?

**Comment by rotx-maxim** [comment]
It's referring to the big README in the training/synthesis repos. We have some pending updates to the document, the preliminary version is here: https://github.com/rotx-maxim/ai8x-synthesis/raw/feature/state/README.pdf

**Comment by sonebu** [comment]
thanks a lot
