### ISSUE TITLE
Problem with the trying out the demo exampels some thing with the ports dont work

### ISSUE THREAD

**Issue by Jan08** [MaximIntegratedAI/MaximAI_Documentation#43]
Hi there,
I want to try out the examples on my new MAX78000 Feather board. I followed the instructions and all works right until the point: 

> _target remote localhost:3333_

I always get the error:

> _localhost:3333: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte._

Sorry, I don't know why it is in German, but it means:

> _localhost:_ 3333: A connection could not be established because the target computer refused to connect._

On step before the terminal also gives slightly different feed back

> _Info : Listening on port 6666 for tcl connections
> Info : Listening on port 4444 for telnet connections
> Info : CMSIS-DAP: SWD  Supported
> Info : CMSIS-DAP: FW Version = 0254
> Info : CMSIS-DAP: Serial# = 044400010185cc7e00000000000000000000000097969906
> Info : CMSIS-DAP: Interface Initialised (SWD)
> Info : SWCLK/TCK = 1 SWDIO/TMS = 1 TDI = 0 TDO = 0 nTRST = 0 nRESET = 1
> Info : CMSIS-DAP: Interface ready
> Info : clock speed 2000 kHz_

This is the end the last lines are missing, especially the one with: listening for port 3333
I hope you can help me out!
Thanks a lot!

**Comment by Jake-Carter** [comment]
Hello,

This is typically a result of low-power lockout.  If firmware is flashed to the device that puts the micro core in low-power mode before the debugger can connect, then the debugger will bounce off of the SWD port with the same error as if the micro was powered off or disconnected.  

You'll notice in our example code that we have a 2s delay placed at the beginning of the code to give the debugger a window to connect.  If you're working with one of our example projects, you can try using the reset button (SW4).  The reset signal resets the program counter to 0 and restarts the firmware.  Push SW4, then immediately try to connect from GDB with `target remote localhost:3333`.  If you time it right, GDB should hit the delay window in the example code and connect successfully.

Failing that, please follow the instructions under "How to Unlock a MAX78000 That Can No Longer Be Programmed" [here](How to Unlock a MAX78000 That Can No Longer Be Programmed).  This will effectively wipe the flash memory on the micro completely and allow you to start fresh from a blank slate.

**Comment by Jan08** [comment]
Thanks, that solved the problem. I didn't expect, that the deep sleep mode ignores even the programmer.

**Comment by kpahwa16** [comment]
I am still facing this issue although I have tried pressing SW4 but when I run the openocd command, it throws up  'Examination Failed, GDB will be halted, polling again in 6300 ms'', 

Also regarding the other solution for  unlocking the board, I am not able understand the part related to Maintenance drive where in we have to drag and drop the binary file. How is the Maintenance drive created. Do we have to manually create it inside Daplink folder?

**Comment by maximreza** [comment]
Hello, could you please provide the firmware revision for the DAPLINK firmware?
If you normally connect the board to your host and open the DAPLINK drive you should see a DETAILS.txt. please provide us with the content of this file. here is an example from mine:

"# DAPLink Firmware - see https://mbed.com/daplink
Unique ID: 0444000127fc8a0100000000000000000000000097969906
HIC ID: 97969906
Auto Reset: 1
Automation allowed: 1
Overflow detection: 1
Daplink Mode: Interface
Interface Version: 0254
Git SHA: 3e2aec98ec8e1bc63fe786f09d707a9ca537d8e4
Local Mods: 0
USB Interfaces: MSD, CDC, HID, WebUSB
Interface CRC: 0x0470b188
Remount count: 0
URL: http://www.maximintegrated.com/max78000"
