### ISSUE TITLE
Installation for Feather board (Linux)

### ISSUE THREAD

**Issue by Doruk-Dilmen** [MaximIntegratedAI/MaximAI_Documentation#48]
Is it only installation for Evaluation Kit? Can I install for Feather board on linux?

**Comment by Jake-Carter** [comment]
Hi @Doruk-Dilmen,

Our tools fully support both the EVKIT and the Feather board.  The same installation instructions apply for both.

To build code for the Feather board, you just need to set the `BOARD` variable in your project's Makefile.  Ex:
![image](https://user-images.githubusercontent.com/38844790/160176267-04c8e0fc-4733-4a9b-8fbc-8ccc4c61e181.png)
