### ISSUE TITLE
Model transformation problem

### ISSUE THREAD

**Issue by ct1tc** [MaximIntegratedAI/MaximAI_Documentation#53]
Why is the number of input channels of layer 5 (flat layer) and the number of output channels of the previous layer equal to 48, but the error display should be set to 3 processor
![image](https://user-images.githubusercontent.com/33993421/173280936-80defc13-4997-4158-811b-a5baa123a02a.png)
![image](https://user-images.githubusercontent.com/33993421/173280990-b1fa60ed-b763-41e8-9559-bfc8ecc732fa.png)
![image](https://user-images.githubusercontent.com/33993421/173281019-a163efb0-2b5e-4b35-8b95-ea4471240e74.png)

**Comment by ermanok** [comment]
Hi ct1tc,

Could you please give some details about how you get this error? It seems either your model checkpoint or sample data is not in the form of you expect.
