### ISSUE TITLE
question regarding YAML 

### ISSUE THREAD

**Issue by hyunjongL** [MaximIntegratedAI/MaximAI_Documentation#55]
Is this note to prevent overwriting data in the memory instance?
Lantency-wise, I don't think there will be any difference. Or is there any memory synchronization issue when using overlapping memory instances?

Note 1: If possible, try to use processors with non-overlapping memory instances (4 processors share the same memory instance) in consecutive layers (e.g. processors: 0x0000000000000001 in layer 1 and 0x00000000000ffff0 in layer 2)

**Comment by rotx-maxim** [comment]
There is no latency difference. Following this advice will make it easier to "balance" the weight memory utilization. I'll ask to add some clarification to this statement.

**Comment by rotx-maxim** [comment]
See #56

**Comment by hyunjongL** [comment]
Thanks, it totally makes sense.
