### ISSUE TITLE
How to program MAX78000 directly from the SWD program?

### ISSUE THREAD

**Issue by emrealabay** [MaximIntegratedAI/MaximAI_Documentation#57]
In MAX78000FTHR, MAX32625 is being used for programming? Can i directly program the MAX78000 without MAX32625 while using the SWDIO&SWCLK pins directly?
 For example: Can i use FT2232H FTDI with   TMS-->SWDIO, TCK-->SWCLK connections & OpenOCD ?
How should be the openOCD steps for programming MAX78000 with SWD?

**Comment by aniktash** [comment]
@jessexm, could you please help?

**Comment by jessexm** [comment]
The MAX78000FTHR was not designed for this mode of operation, but it may be possible by gaining access to the MAX78000 SWD signals and preventing the onboard MAX32625 from interfering with an external debugger.

In addition to SWD debugging the onboard MAX32625PICO firmware insures the MAX78000 bootloader is not activated at power-on or external resets. Bootloader activation occurs when both SWDCLK and UART0.RX are low when RSTN is deasserted.

The unpopulated SWD connector J2 can provide access to the MAX78000 SWD signals as it is connected in parallel with the onboard MAX32625.

Preventing the MAX32625 from driving the MAX78000 SWD signals will require hardware modification or specialized MAX32625PICO firmware.


With the external SWD hardware connected you will need to modify the OpenOCD interface option to specify your SWD hardware. The onboard MAX32625PICO is specified with `-f interface/cmsis-dap.cfg`, your SWD hardware documentation should specify the configuration file to use.
