### ISSUE TITLE
Power numbers on PMON display is not accurate.

### ISSUE THREAD

**Issue by chay93** [MaximIntegratedAI/MaximAI_Documentation#59]
Hello Maxim team 

So I was trying to run the kws20_demo application from the Eclipse SDK and getting the Power measurements as shown in the attached image below, but the power measurements are not getting tallyed with the numbers that you showed in this page. [https://www.maximintegrated.com/en/design/technical-documents/app-notes/7/7417.html] 
![20221115_162430](https://user-images.githubusercontent.com/87551317/202057407-7aa9df91-7887-48ec-bcef-c86f699e478b.jpg)

**Comment by aniktash** [comment]
To measure the power, you need to set the #define SLEEP_MODE  to 2 and #define ENERGY.  Then you need to measure the system power during different operation cycles of the application. If you want to measure just the inference power, you can regenerate the known answer test code in the synthesis tool using --energy.  In this case, the power monitor should be in CNN power. For more info on how to use power monitor, please see: https://github.com/vicloginov/MaximAI_Documentation/blob/master/MAX78000_Evaluation_Kit/MAX78000%20Power%20Monitor%20and%20Energy%20Benchmarking%20Guide.md#windowed-energy-accumulation

**Comment by chay93** [comment]
So just to measure the inference power I should use _python ai8xize.py --energy_ or what is the full command for utilize this option.

**Comment by chay93** [comment]
I was able to generate a folder using this command _python ai8xize.py --test-dir demos --prefix ai85-kws20 --checkpoint-file trained/ai85-kws20-qat8-q.pth.tar --config-file networks/kws20-hwc.yaml --device MAX78000 --energy_

**Comment by chay93** [comment]
Hello team
I would like to use both ARM and RISC-V processors, and I have used the following command to build the necessary scripts, but unable to launch the model.
the command :  _python ai8xize.py --checkpoint-file trained/ai85-kws20_v3-qat8-q.pth.tar --config-file networks/kws20-v3-hwc.yaml --test-dir /mnt/c/MaximSDK/Examples/MAX78000/CNN --prefix kws20_v3_energy_riscv --energy --device MAX78000 --deepsleep --riscv --riscv-debug_

Tell me how to use both ARM and RISC-V processors
