### ISSUE TITLE
How to use ARM and RISC-V processors in MAX78000

### ISSUE THREAD

**Issue by chay93** [MaximIntegratedAI/MaximAI_Documentation#60]
the command I have used to use the RISC-V processor along with the ARM is as follows, but once I try to launch the application in my Eclipse SDK, I get an error. Can anyone help me understand how to use ARM and RISC-VC processors?

Command : _python ai8xize.py --checkpoint-file trained/ai85-kws20_v3-qat8-q.pth.tar --config-file networks/kws20-v3-hwc.yaml --test-dir /mnt/c/MaximSDK/Examples/MAX78000/CNN --prefix kws20_v3_energy_riscv --energy --device MAX78000 --deepsleep --riscv --riscv-debug_

**Comment by vicloginov** [comment]
Thank you for letting us know. We will update documentation to clarify how to program and debug an application which uses ARM and RISC-V cores.

**Comment by Jake-Carter** [comment]
Hi @chayy93 Dual-core debugging in Eclipse is currently not very well supported, and essentially involves running two separate Eclipse instances.  Fundamentally, you'll need to debug the Arm M4 core first and let it spin up the RISC-V core.  Then, a separate debugger instance needs to be launched on a different port to connect to the RISC-V JTAG port and issue a soft-reset to it.

I have documented the procedure for VS Code [here](https://github.com/Analog-Devices-MSDK/VSCode-Maxim/wiki/RISC-V-Debugging-Guide), which should work as an alternative.

I'm currently working on an updated universal SDK user guide, and additional dual-core debugging documentation is in progress.  (https://github.com/Jake-Carter/msdk/blob/dev/userguide/USERGUIDE.md)

**Comment by vicloginov** [comment]
Hi **@chayy93**, please check PR#268 https://github.com/Analog-Devices-MSDK/msdk/pull/268 for corrected docs
