### ISSUE TITLE
Unable to run the demos on MAX78000

### ISSUE THREAD

**Issue by chayy93** [MaximIntegratedAI/MaximAI_Documentation#61]
Hello Maxim team

I'm encountering an error while running the demos _'kws20_demo-riscv'_ and _'faceid_evkit-riscv'_ in Eclipse Maxim SDK, saying there are errors in the existing demos and it is unable to launch the demos. Any help in order to run these demos?

**Comment by vicloginov** [comment]
Thank you for letting us know. We will update documentation to clarify how to program and debug an application which uses ARM and RISC-V cores.

**Comment by Jake-Carter** [comment]
Hi @chayy93 Dual-core debugging in Eclipse is currently not very well supported, and essentially involves running two separate Eclipse instances.  Fundamentally, you'll need to debug the Arm M4 core first and let it spin up the RISC-V core.  Then, a separate debugger instance needs to be launched on a different port to connect to the RISC-V JTAG port and issue a soft-reset to it.

I have documented the procedure for VS Code [here](https://github.com/Analog-Devices-MSDK/VSCode-Maxim/wiki/RISC-V-Debugging-Guide), which should work as an alternative.

I'm currently working on an updated universal SDK user guide, and additional dual-core debugging documentation is in progress.  (https://github.com/Jake-Carter/msdk/blob/dev/userguide/USERGUIDE.md)
