### ISSUE TITLE
Trouble with SWD

### ISSUE THREAD

**Issue by viviand0097** [MaximIntegratedAI/MaximAI_Documentation#63]
I am currently doing a project which required me to develop a custom PCB with the new MAX78002.
 
Only when I tried to program it with the MAX32625PICO, I got a flash error: Error connecting DP: cannot read IDR. The SWD pins are connected and traced to an header. The datasheet/manual is not clear about if I need to reset before flash or that only the SWDIO and SWDCLK are good enough for flashing.
 
When debugging I found out that I needed a pullup on the uart0_rx or swdclk. Adding this and following the bootloader instructions (pulling activation pins low and reset) I got the following prompt on the UART0_Tx pin. The strange thing is that the reset pin is not working, only power on/off will lead to this result:
 
ULDR> (means: bootloader state is unlocked, swd pins activated) or in HEX 00 55 4C 44 52 3E 20 00 A0 02 00 01 03 0B A0 04 00 00 02 00 0A 01 00.  Thus beside the message I also got some other data.
 
From this I could conclude that the chip is well soldered and that the chip is working. In both bootloader and non-bootloader mode the chip is sadly not programmable.
 
Could you tell me how to program the MCU with SWD?

**Comment by Jake-Carter** [comment]
Hi @viviand0097 

Yes, a properly connected RSTN line is required to flash the MAX78002.

To flash the MAX78002 over SWD:
1. Ensure UART0_RX (P0_0) has a pull-up to prevent activation of the bootloader on startup (as you've done).
2. Ensure RSTN has a pull-up.
3. Supply power to the MAX78002.  On the EVKIT that gives:
    - VCOREA = 1.2V
    - VCOREB = 1.1V
    - VDDA = 1.9V
    - VDDB = 0V (should be irrelevant - this is just USB transceiver power).
    - VDDIO = 1.8V
    - VDDIOH = 3.3V
4. Execute the flash procedure using our tools.  See the [MSDK User Guide](https://analog-devices-msdk.github.io/msdk/USERGUIDE/) for more details depending on your preferred IDE.

For your reference I've attached a logic analyzer ([Saleae](https://www.saleae.com/downloads/)) capture of RSTN, SWDIO, and SWDCLK after [flashing over the command-line](https://analog-devices-msdk.github.io/msdk/USERGUIDE/#flashing-on-the-command-line), which gives the cleanest traces.  IDEs will add some extra reset/communication sequences that muddy the waters a little for troubleshooting.

[MAX78002_Flash_SWD_Hello_World.zip](https://github.com/MaximIntegratedAI/MaximAI_Documentation/files/10701411/MAX78002_Flash_SWD_Hello_World.zip)

At a high level, this is what it should a successful flash-verify should look like (Note RSTN):
![image](https://user-images.githubusercontent.com/38844790/217936526-a8c471a8-d5de-4e81-a250-393d6d382e92.png)

With the following OpenOCD output:
```shell
$ openocd -s %MAXIM_PATH%/Tools/OpenOCD/scripts -f interface/cmsis-dap.cfg -f target/max78002.cfg -c "program build/Hello_World.elf verify exit"

Open On-Chip Debugger 0.11.0+dev-g56a818e4c (2022-11-16-05:46)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
DEPRECATED! use 'adapter driver' not 'interface'
Info : CMSIS-DAP: SWD  supported
Info : CMSIS-DAP: FW Version = 1.0
Info : CMSIS-DAP: Interface Initialised (SWD)
Info : SWCLK/TCK = 0 SWDIO/TMS = 1 TDI = 0 TDO = 0 nTRST = 0 nRESET = 0
Info : CMSIS-DAP: Interface ready
Info : clock speed 2000 kHz
Info : SWD DPIDR 0x2ba01477
Info : max32xxx.cpu: Cortex-M4 r0p1 processor detected
Info : max32xxx.cpu: target has 6 breakpoints, 4 watchpoints
Info : starting gdb server for max32xxx.cpu on 3333
Info : Listening on port 3333 for gdb connections
Info : SWD DPIDR 0x2ba01477
target halted due to debug-request, current mode: Thread 
xPSR: 0x81000000 pc: 0x0000fff4 msp: 0x20003ff0
** Programming Started **
** Programming Finished **
** Verify Started **      
** Verified OK **       
shutdown command invoked
```

**Comment by viviand0097** [comment]
@Jake-Carter 
Thank you very much for your detailed reply. For now, I will continue to work with the ev-kit which just arrived for me.

Why does the MaximSDK not have the kws20 demo CNN in examples for the MAX78002? Are the examples from the MAX78000 compatible with the ev-kit of the MAX78002? I was able to build and flash the MAX78002 examples, but faced errors when I tried to flash the kws from the 78000 examples to the ev-kit of the 78002.

**Comment by viviand0097** [comment]
@Jake-Carter Thank you very much for your reply.

**Comment by Chielvdiepen** [comment]
@Jake-Carter 

Why is there a pull-up needed at the reset? because it already has an internal 25k pullup according to the datasheet.

**Comment by Jake-Carter** [comment]
You're right, I should have said "ensure RSTN _is pulled up_".

If you're connecting RSTN directly then you can rely on the 25K internal pull-up.  Just ensure that your debug adapter and config is not holding the line low for anything but the initial reset.  There are some known limitations of our debug hardware (see [debugger limitations of the MAX78002](https://github.com/MaximIntegratedAI/MaximAI_Documentation/tree/master/MAX78002_Evaluation_Kit#debugger-limitations-of-the-max78002)) - primarily the micro core is not accessible over SWD _while RSTN is held low_.  As you can see in the logic traces above we drive the initial reset pulse, release RSTN, then immediately attempt to reconnect to the SWD to begin the flash sequence.

In some cases an external pull-up is required.  For example, we drive RSTN through an open-drain buffer on the MAX78002EVKIT.  So R91 is required to pull up the buffer.

![image](https://user-images.githubusercontent.com/38844790/220190843-cebe52fc-21aa-496b-8879-f06ae188bf45.png)
