### ISSUE TITLE
MAX78000FTHR will shut down automaticall 

### ISSUE THREAD

**Issue by dd87350** [MaximIntegratedAI/MaximAI_Documentation#64]
1."Completed"Download the "max32625_max78000fthr_if_crc_v1.0.2.bin" file from this link. 
2."Completed"Connect the included micro-USB cable to the MAX78000FTHR without connecting the other side of the cable to your host PC yet.
3."Completed"Press and hold the SW5 pushbutton.
4."Completed"While holding down the SW5 pushbutton connect the other side of the micro-USB cable to your host PC.
Keep the pushbutton held down until the red LED (D3) on the MAX78000FTHR blinks and becomes solid.
5. "Completed"A "MAINTENANCE" drive should now appear on your file system.

**Issue: After about 5 seconds, the red light disappears and MAX78000FTHR shuts down (enters standby mode).**
Please help me...Thank you

**Comment by dd87350** [comment]
> 你好@dd87350，我以前沒見過這個問題...
> 
> 您使用的是什麼操作系統？
> 
> 您能否將 MAINTENANCE 驅動器中出現的“DETAILS.TXT”文件的內容附加到此工單中？您應該能夠在驅動器消失之前快速打開文件。
> 
> 測試新的MAX78000FTHR 剛開箱，我的內容是：
> 
> ```
> # DAPLink Firmware - see https://mbed.com/daplink
> Unique ID: 000000001452035100000000000000000000000097969904
> HIC ID: 97969904
> Auto Reset: 0
> Automation allowed: 1
> Overflow detection: 0
> Daplink Mode: Bootloader
> Bootloader Version: 0243
> Git SHA: 85b1393b8062b05e6db2b154870f4619a29d48a5
> Local Mods: 1
> USB Interfaces: MSD
> Bootloader CRC: 0x8f60c976
> Interface CRC: 0x0470b188
> Remount count: 0
> ```
Thank you for your response. I apologize for taking so long to reply. This is the content that I saw before closing.

# DAPLink Firmware - see https://mbed.com/daplink
Unique ID: 000000001aa6030400000000000000000000000097969904
HIC ID: 97969904
Auto Reset: 0
Automation allowed: 1
Overflow detection: 0
Daplink Mode: Bootloader
Bootloader Version: 0243
Git SHA: 85b1393b8062b05e6db2b154870f4619a29d48a5
Local Mods: 1
USB Interfaces: MSD
Bootloader CRC: 0x8f60c976
Interface CRC: 0xb61afbb5
Remount count: 0

**Comment by Jake-Carter** [comment]
There is a mismatch in the interface CRC between my working board and yours `0x0470b188` vs `0xb61afbb5`.  This indicates a possible flash failure and corruption of the DAPLINK firmware.  It would have had to happen at the factory, so this should be covered under defective part failure by your distributor.

I would suggest initiating the RMA procedure for the board with the distributor you purchased it from and request a new board
