### ISSUE TITLE
code for video streaming with either Pcam or OVM7652 for neural network inference

### ISSUE THREAD

**Issue by nikky4D** [MaximIntegratedAI/MaximAI_Documentation#66]
is there a sample of how to do video streaming with Pcam or OVM7692. I've used the ImgCapture project in the MSDK examples but it says not to use it for neural networks input. 

I've also tried the CameraIF project in the MSDK examples but I was only able to display the image on the device but not get a sample onto the PC. The program stalled at the comManager.find_sync() step.

**Comment by vicloginov** [comment]
I fixed a bug in main.c file of MAX78002 CameraIF example. Please use attached file. Now you can stream images to PC captured by OV7692 camera sensor.  The MAX78002 MSDK repo will be updated soon.
[main.zip](https://github.com/MaximIntegratedAI/MaximAI_Documentation/files/11457026/main.zip)

**Comment by nikky4D** [comment]
Thanks, I will try this out.

**Comment by Jake-Carter** [comment]
Hi @nikky4D, also be aware that I have a pull request open with some major fixes and improvements to our MAX78002 image pipeline.  It includes a new example for sending Pcam images to our latest object detection network.

* https://github.com/Analog-Devices-MSDK/msdk/pull/583
