### ISSUE TITLE
Constant overflow of streaming buffers from camera_write_reg(0x11, 0x0) to camera_write_reg(0x11, 0xF)

### ISSUE THREAD

**Issue by kirilllzaitsev** [MaximIntegratedAI/MaximAI_Documentation#67]
Hi, my setup matches the one from the aisegment_demo example.
Setting multiple values in `camera_write_reg(0x11, x)` under `#if defined(CAMERA_OV7692) && defined(STREAM_ENABLE)`
leads to the same output:
```
Portrait Segmentation Feath�

Camera Example
Camera I2C slave address: 3c
Camera ID detected: 7fa2
Init Camera
Start capturing
OVERFLOW = 351
```
The overflow value is constant for several `camera_write_reg(0x11, x)` I tried from 0x0 to 0xF. Could you help?

**Comment by Jake-Carter** [comment]
Hi @kirilllzaitsev 

I would suspect hardware failure on the camera module itself.  To confirm, you can try this binary which I've tested on my MAX78000EVKIT.

[aisegment_unet-demo_MAX78000EVKIT.zip](https://github.com/MaximIntegratedAI/MaximAI_Documentation/files/11986337/aisegment_unet-demo_MAX78000EVKIT.zip)

Be sure that you have your camera module in the correct orientation (lens facing outwards from the board)

If this binary fails as well, please email your contact and shipping info to jake.carter@analog.com.  We will contact you to provide additional tested samples of the OV7692 camera module.

**Comment by kirilllzaitsev** [comment]
Hi @Jake-Carter, I'm sorry, I don't have the board anymore (it was a temporary rent)

**Comment by Jake-Carter** [comment]
I'll close this issue out as suspected hardware failure on the camera module
