### ISSUE TITLE
MAX78000FTHR does not show itself as USB device

### ISSUE THREAD

**Issue by danielfhnw** [MaximIntegratedAI/MaximAI_Documentation#68]
To set up my MAX78000FTHR board I followed the "Getting Started with the MAX78000FTHR". After plugging it into my computer there is no device showing up, neither a "MAINTENANCE" with pushbutton SW5 pressed nor a "DAPLINK" without anything pressed. The red LED (D3) also never turns on. (similar issue already mentioned in #62)

I already exchanged the USB cable, the USB port on the computer and set up another board successfully. Therefore I rule out everything but the board itself and conclude that something is broken.

Is there anything else I can try or do I have to get a new one?

**Comment by rotx-maxim** [comment]
Since you have another board that's working, and based on your description, I'm afraid we'll have to send you a new board. Please let us know how to contact you for shipping information.

**Comment by danielfhnw** [comment]
I sent you an email to the address linked to your github account on friday. If you have not received it, you can contact me on daniel.jakober@fhnw.ch.
