### ISSUE TITLE
MAX78000 Latest Manual Request

### ISSUE THREAD

**Issue by JuledLikalla** [MaximIntegratedAI/MaximAI_Documentation#69]
Hello 

I  am a student studying MSc in Embedded Computing Systems in University of Southampton, Uk.

I am working on my masters project and I am using MAX78000 evaluation kit to execute an optimised CNN using its CNN accelerator.

The user guide of MAX78000 that I am currently using (max78000 user guide UG7456; Rev 0; 7/2021) doesn't explain all the registers and has a lot of typos and errors.

I was wondering if you could provide an updated version of the User's Guide of MAX78000 SoC or a more detailed manual for the CNN accelerator.

It would be very helpful.

Also I tried to open the documentation using the links here:
https://github.com/Analog-Devices-MSDK/MAX78000_SDK/tree/master/Documentation
but they do not work.

Thanks

**Comment by cwarer1** [comment]
Hello. The best way to understand the register usage for the MAX78000 CNN is to look at the source code of the "izer" tool, which can be found [here](https://github.com/MaximIntegratedAI/ai8x-synthesis).

**Comment by JuledLikalla** [comment]
Thanks for the reply!
