### ISSUE TITLE
MSDK User Guide link incorrect

### ISSUE THREAD

**Issue by viisatadi** [MaximIntegratedAI/MaximAI_Documentation#75]
Hyperlink in readme under "Software Development / Setup" stating "...See the [MSDK User Guide](https://analog-devices-msdk.github.io/msdk/USERGUIDE/) for detailed documentation on installation, setup, and getting started." is incorrect. 

MSDK user guide link should be: https://analogdevicesinc.github.io/msdk//USERGUIDE/

**Comment by Jake-Carter** [comment]
Thanks @viisatadi
